name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
